version: "3.8"

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=whoof
    volumes:
      - postgres-data:/var/lib/postgresql/data

  integration-tests:
    build:
      dockerfile: ./Dockerfile.tests
    volumes:
      - ./test-reports:/app/test-reports
    depends_on:
      - postgres

volumes:
  postgres-data: