FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["src/apps/Whoof.Api/Whoof.Api.csproj", "src/apps/Whoof.Api/"]
RUN dotnet restore "src/apps/Whoof.Api/Whoof.Api.csproj"
COPY . .
WORKDIR "/src/src/apps/Whoof.Api"
RUN dotnet build "Whoof.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Whoof.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Whoof.Api.dll"]
