name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Compose
        uses: isbang/compose-action@v1.5.0
        with:
          down-flags: "--volumes"
      - name: Integration Tests
        run: |
          dotnet test \
            --logger trx \
            --logger "console;verbosity=detailed" \
            --settings "runsettings.xml" \
            --results-directory test-reports
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=graduenz
            -Dsonar.projectKey=graduenz_whoof-aspnetcore
            -Dsonar.branch.name=${{ github.ref }}
            -Dsonar.cs.opencover.reportsPaths=**/*/coverage.opencover.xml
            -Dsonar.cs.vstest.reportsPaths=**/*/*.trx
            -Dsonar.exclusions=samples/**/*.cs,src/common/Whoof.Migrations/**/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}